services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg.setka-app.local/setka-app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      HISTFILE: /app/.local/.bash_history
    ports:
     - 3080:8080
    networks:
     default:
       aliases:
         - api.setka-app.local
    volumes:
     - ./:/app
     - gradle-home:/root/.gradle
    depends_on:
     - pg
    stdin_open: true
    tty: true

  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: setka-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d flux
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - pg.setka-app.local

volumes:
  gradle-home:
  pg:

networks:
  default:
    name: setka-app-dev
